### ISSUE TITLE
webservice ERRSIS041

### ISSUE THREAD

**Issue by IDaniel8** [buuum/Redsys#1]
hi im trying to stablish a connection on webservice on redsys with this library i put
```
<?php
include_once('./Redsys.php');

$redsys = new \Buuum\Redsys('sq7HjrUOBfKmC576ILgskD5srU870gJ7');

try {
    $redsys->setMerchantcode('999008881');
    $redsys->setAmount(rand(10,600));
    $redsys->setOrder(time());
    $redsys->setTerminal('1');
    $redsys->setCurrency(978);

    $redsys->setPan('4548812049400004');
    $redsys->setExpiryDate('2012');
    $redsys->setCVV('123');

    $redsys->setTransactiontype('A');
    $redsys->setIdentifier('REQUIRED');

    $result = $redsys->firePayment();

} catch (Exception $e) {
    echo $e->getMessage();
    die;
}

print_r($result);

```
and it prints out
`Array ( [error] => 1 [code] => SIS041 [Ds_Amount] => 56300 [Ds_Currency] => 978 [Ds_Order] => 1500570448 [Ds_Signature] => zIADS/bBap+OZWyZAMokBwV81B1LJH4mNidB8LMvkmM= [Ds_MerchantCode] => 999008881 [Ds_Terminal] => 1 [Ds_Response] => 0000 [Ds_AuthorisationCode] => 777295 [Ds_TransactionType] => A [Ds_SecurePayment] => 0 [Ds_Language] => 1 [Ds_CardNumber] => 454881******0004 [Ds_ExpiryDate] => 2012 [Ds_Merchant_Identifier] => c3d92126c7db0845f1c942064d61aa82f8badafd [Ds_MerchantData] => Array ( ) [Ds_Card_Country] => 724 [Ds_Card_Brand] => 1 )`

what im doing wrong? im newb in SOAP

**Comment by cris890** [comment]
I am having exactly the same problem and I am sending all the parameters correctly.

$key='sq7HjrUOBfKmC576ILgskD5srU870gJ7';
$redsys = new \Buuum\Redsys($key);

$redsys->setMerchantcode('348666025');
$redsys->setAmount($subscription->price);
$redsys->setOrder(time());
$redsys->setTerminal('1');
$redsys->setCurrency(978);
$redsys->setTransactiontype('A');
$redsys->setProductDescription('test');
$redsys->setIdentifier($subscription->merchant_identifier);
$redsys->setMerchantDirectPayment(true);

and always get:

array:18 [▼
  "error" => true
  "code" => "SIS0041"
  "Ds_Amount" => "4839"
  "Ds_Currency" => "978"
  "Ds_Order" => "1559255860"
  "Ds_Signature" => "sASLR1rK7nNYcuTKEIK/oqOxKyM7R6btojvdGz3qy4c="
  "Ds_MerchantCode" => "348666025"
  "Ds_Terminal" => "1"
  "Ds_Response" => "0000"
  "Ds_AuthorisationCode" => "660204"
  "Ds_TransactionType" => "A"
  "Ds_SecurePayment" => "0"
  "Ds_Language" => "1"
  "Ds_CardNumber" => "454881******0004"
  "Ds_Merchant_Identifier" => "119645a46b5ed6a85cc698ba29248f6badda5609"
  "Ds_MerchantData" => []
  "Ds_Card_Country" => "724"
  "Ds_Card_Brand" => "1"
]

what is the problem?
